export const AUTH_KEYS = {
    LOGIN_STATE: 'RECOIL::AUTH:://LOGIN_STATE',
    USER_AUTHENTICATED_STATE: 'RECOIL::AUTH:://USER_AUTHENTICATED_STATE',
    FORGOT_PSWD_SCREEN_STATE: 'RECOIL::AUTH:://FORGOT_PSWD_SCREEN_STATE',
}
export const SCREEN_MANAGER_KEYS = {
    ACTIVE_MENU_STATE: 'RECOIL::SCREEN_MANAGER:://ACTIVE_MENU_STATE',
    SCREEN_SIZE_STATE: 'RECOIL::SCREEN_MANAGER:://SCREEN_SIZE_STATE',
    CURRENT_MODE_STATE: 'RECOIL::SCREEN_MANAGER:://CURRENT_MODE_STATE',
    CURRENT_COLOR_STATE: 'RECOIL::SCREEN_MANAGER:://CURRENT_COLOR_STATE',
    THEME_SETTINGS_STATE: 'RECOIL::SCREEN_MANAGER:://THEME_SETTINGS_STATE',
    IS_CLICKED_STATE: 'RECOIL::SCREEN_MANAGER:://IS_CLICKED_STATE',
    INITIAL_STATE: 'RECOIL::SCREEN_MANAGER:://INITIAL_STATE',

}
