export enum PERMISSIONS {
    // USERS
    CREATE_USER = 'CAN::USERS:://CREATE_USER',
    READ_INFO_USER = 'CAN::USERS:://READ_INFO_USER',
    GET_USERS = 'CAN::USERS:://GET_USERS',
    UPDATE_USER = 'CAN::USERS:://UPDATE_USER',
    // ETC
    MANAGE_GAP = 'CAN::GAP:://MANAGE_GAP',
}

